// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvwu7U8pW0PldxcOh_41c1c--CrN66vZw',
    appId: '1:864368728057:web:2efb77270eed86e1514f28',
    messagingSenderId: '864368728057',
    projectId: 'to-do-list-4d640',
    authDomain: 'to-do-list-4d640.firebaseapp.com',
    storageBucket: 'to-do-list-4d640.appspot.com',
    measurementId: 'G-KY1K2ESC9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArGOFIlSLHiTvRijalxRZXeJY7ucwIMgk',
    appId: '1:864368728057:android:1c9a9aa753e3b975514f28',
    messagingSenderId: '864368728057',
    projectId: 'to-do-list-4d640',
    storageBucket: 'to-do-list-4d640.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRO0D0WcKkWONyFjK_9TUG7RjWW555If8',
    appId: '1:864368728057:ios:660340edaa5c2d0c514f28',
    messagingSenderId: '864368728057',
    projectId: 'to-do-list-4d640',
    storageBucket: 'to-do-list-4d640.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRO0D0WcKkWONyFjK_9TUG7RjWW555If8',
    appId: '1:864368728057:ios:660340edaa5c2d0c514f28',
    messagingSenderId: '864368728057',
    projectId: 'to-do-list-4d640',
    storageBucket: 'to-do-list-4d640.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvwu7U8pW0PldxcOh_41c1c--CrN66vZw',
    appId: '1:864368728057:web:29c7dde491aea840514f28',
    messagingSenderId: '864368728057',
    projectId: 'to-do-list-4d640',
    authDomain: 'to-do-list-4d640.firebaseapp.com',
    storageBucket: 'to-do-list-4d640.appspot.com',
    measurementId: 'G-M87NLNEXGS',
  );
}
